# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint_yml:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install --user yamllint && yamllint co2eq/**/*.yml

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "playground/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: touch integrations/env.json
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - playground/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "playground/yarn.lock" }}
      # run linter
      - run: yarn lint
      # run tests
      - run: yarn test

workflows:
  version: 2
  lint_yml_and_build:
    jobs:
      - lint_yml
      - build
